language: generic

# explicitly request container-based infrastructure
sudo: false

matrix:
  include:
    - env: CABALVER=3.2 GHCVER=8.10.2
      addons: {apt: {packages: [cabal-install-3.2,ghc-8.10.2,happy-1.19.5],sources: [hvr-ghc]}}
    - env: CABALVER=3.0 GHCVER=8.8.4
      addons: {apt: {packages: [cabal-install-3.0,ghc-8.8.4,happy-1.19.5],sources: [hvr-ghc]}}
    - env: CABALVER=2.4 GHCVER=8.6.5
      addons: {apt: {packages: [cabal-install-2.4,ghc-8.6.5,happy-1.19.5],sources: [hvr-ghc]}}

before_install:
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal v2-update
 - cabal v2-configure --enable-tests --enable-benchmarks -v2
 - cabal v2-install --only-dependencies

script:
 - cabal v2-build
 - cabal v2-test
 - cabal sdist   # tests that a source-distribution can be generated
