name:           stuck-macros
version:        0.1
github:         gelisam/stuck-macros
author:         David Christiansen <david@davidchristiansen.dk>,  Samuel Gélineau <gelisam@gmail.com>
maintainer:     David Christiansen <david@davidchristiansen.dk>,  Samuel Gélineau <gelisam@gmail.com>
ghc-options: -Wall
dependencies:
  - base
  - containers
  - directory
  - extra
  - filepath
  - lens
  - megaparsec
  - mtl
  - prettyprinter
  - text
library:
  source-dirs: src
executables:
  stuck-macros-repl:
    main:        Main.hs
    source-dirs: stuck-macros
    dependencies:
      - optparse-applicative
      - stuck-macros
tests:
  stuck-macro-tests:
    main:
      tests/Test.hs
    dependencies:
      - call-stack
      - deepseq
      - stuck-macros
      - tasty
      - tasty-hunit
