name:           stuck-macros
version:        0.1
github:         gelisam/stuck-macros
author:         David Christiansen <david@davidchristiansen.dk>,  Samuel Gélineau <gelisam@gmail.com>
maintainer:     David Christiansen <david@davidchristiansen.dk>,  Samuel Gélineau <gelisam@gmail.com>
executables:
  stuck-macros:
    main:        Main.hs
    dependencies:
      - base
      - containers
      - megaparsec
      - mtl
      - text
    source-dirs: src
